### ISSUE TITLE
Added unmanaged windows nodes

### ISSUE THREAD

**Issue by hlmuludiang** [terrablocks/aws-eks-unmanaged-node-group#1]
Hi!

Does your module also allow the addition of unmanaged windows nodes to a eks cluster?  I am able to create Windows nodes, but it looks like they are not being attached to the target cluster.

Thanks,

Hilary

**Comment by paliwalvimal** [comment]
@hlmuludiang Unmanaged nodes do not automatically attach to the cluster. You need to follow additional steps to attach nodes to the cluster. Please refer to the [post steps](https://github.com/terrablocks/aws-eks-unmanaged-node-group#important-post-steps-source-aws) mentioned in the readme or visit AWS doc.
